### ISSUE TITLE
基于 Jenkins 的 CI/CD(一)

### ISSUE THREAD

**Issue by cnych** [cnych/qikqiak-blog#41]
https://blog.qikqiak.com/post/kubernetes-jenkins1/

**Comment by zhaop33** [comment]
我按照教程设置，salve容器启动起来了，但是与master的连接建立不起来，显示离线状态，我哪里有设置不对吗，那个jnlp端口我也设置成50000了

**Comment by cnych** [comment]
@zhaop33 你50000端口有通过`service`暴露出来吗？看看`slave pod`的日志呢？有没有什么错误信息之类的~

**Comment by zhaop33** [comment]
暴露了，jenkins2      NodePort    10.68.206.234   <none>        8080:30002/TCP,50000:39396/TCP   4d
	TCP port for JNLP agents	指定端口 : 50000
salve控制台没有打印日志，但是我可以进入salve容器内部

**Comment by zhaop33** [comment]
cnych/jenkins:jnlp这个镜像的dockerfile文件可以共享一下吗？我想自定义自己的dockerfile文件

**Comment by cnych** [comment]
相关的文件需要自己下载下来，`Dockerfile`地址：[https://github.com/cnych/kubernetes-learning/blob/master/jenkins/jenkins-slave.Dockerfile](https://github.com/cnych/kubernetes-learning/blob/master/jenkins/jenkins-slave.Dockerfile)

**Comment by zhaop33** [comment]
感谢感谢

**Comment by maxmonkey950** [comment]
你好，我按照这个配置下来报错了。信息如下：kubectl desc 出现以下内容
Events:
  Type     Reason         Age               From                   Message
  ----     ------         ----              ----                   -------
  Normal   Scheduled      1m                default-scheduler      Successfully assigned kube-ops/jnlp-8qxnq to 10.30.54.224
  Warning  InspectFailed  10s (x7 over 1m)  kubelet, 10.30.54.224  Failed to inspect image "cnych/jenkins:jnlp": rpc error: code = Unknown desc = Error response from daemon: readlink /var/lib/docker/overlay2/l: invalid argument
  Warning  Failed         10s (x7 over 1m)  kubelet, 10.30.54.224  Error: ImageInspectError

**Comment by cnych** [comment]
@maxmonkey950 这个应该是你 Docker 的问题，建议重启下 Docker 或者更换一个存储引擎试看看~

**Comment by maxmonkey950** [comment]
找到问题了。我删除了镜像然后重新下载了一次就好了。谢谢




    


在2019年03月14日 10:52，阳明 写道： @maxmonkey950 这个应该是你 Docker 的问题，建议重启下 Docker 或者更换一个存储引擎试看看~

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cnych/qikqiak-blog","title":"cnych/qikqiak-blog","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/cnych/qikqiak-blog"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cnych in #41: @maxmonkey950 这个应该是你 Docker 的问题，建议重启下 Docker 或者更换一个存储引擎试看看~"}],"action":{"name":"View Issue","url":"https://github.com/cnych/qikqiak-blog/issues/41#issuecomment-472684666"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cnych/qikqiak-blog/issues/41#issuecomment-472684666",
"url": "https://github.com/cnych/qikqiak-blog/issues/41#issuecomment-472684666",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wh6585306** [comment]
请问下按照教程部署后，kubectl describe jenkins-6d495f4dd5-fsv9v报一下错误是为啥？
error: the server doesn't have a resource type "jenkins-6d495f4dd5-fsv9v"

**Comment by cnych** [comment]
@wh6585306 命令错了，describe后面要加一个pod，表示describe pod这种资源

**Comment by wh6585306** [comment]
Error from server (NotFound): pods "jenkins-6d495f4dd5-fsv9v" not found
jenkins-6d495f4dd5-fsv9v 是pod name

**Comment by wh6585306** [comment]
搭得好艰难啊，请问能QQ/微信跟您联系吗？

**Comment by cnych** [comment]
@wh6585306 你这个是属于kubernetes的基本操作使用啦，和jenkins还没关系，后面得加上pod的namespace。加我微信吧：iEverything

**Comment by thinkinfinite** [comment]
> @zhaop33
> 暴露了，jenkins2      NodePort    10.68.206.234   <none>        8080:30002/TCP,50000:39396/TCP   4d
> 	TCP port for JNLP agents	指定端口 : 50000
> salve控制台没有打印日志，但是我可以进入salve容器内部

@zhaop33 @cnych 我也遇到了一样的问题，请问怎么解决的喃？

**Comment by shalousun** [comment]
照着文章步骤操作了一遍，最后jenkins slave一直pending, 查看看原因是persistentvolumeclaim "pvc-jnlp-slave-vhw1p" not found，od has unbound immediate PersistentVolumeClaims (repeated 2 times)，这个slave的pvc不知道需要在哪里绑定

**Comment by cnych** [comment]
@shalousun 你是自己挂载了 PVC 吗？正常默认是没有挂载的呀~ 这个提示是因为没有合适的 PV 和 PVC 进行绑定，你可以把你的 slave pod 的 yaml 文件导出来看看~

**Comment by wenpengfan** [comment]
2019-10-21 05:39:46.944+0000 [id=402]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2019-10-21 05:39:56.954+0000 [id=396]	WARNING	o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: jnlp-slave-4cjk4, template=PodTemplate{inheritFrom='', name='jnlp-slave', namespace='kube-ops', label='jnlp-slave', serviceAccount='jenkins', nodeSelector='', nodeUsageMode=NORMAL, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], volumes=[HostPathVolume [mountPath=/var/run/docker.sock, hostPath=/var/run/docker.sock], HostPathVolume [mountPath=/root/.kube, hostPath=/root/.kube]], containers=[ContainerTemplate{name='jnlp-slave', image='cnych/jenkins:jnlp6', workingDir='/home/jenkins', command='', args='', ttyEnabled=true, resourceRequestCpu='', resourceRequestMemory='', resourceLimitCpu='', resourceLimitMemory='', livenessProbe=org.csanchez.jenkins.plugins.kubernetes.ContainerLivenessProbe@46de61b7}]}
java.lang.IllegalStateException: Pod has terminated containers: kube-ops/jnlp-slave-4cjk4 (jnlp, jnlp-slave)
	at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:166)
	at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.periodicAwait(AllContainersRunningPodWatcher.java:187)
	at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.await(AllContainersRunningPodWatcher.java:127)
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:132)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:297)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-10-21 05:39:56.955+0000 [id=396]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent jnlp-slave-4cjk4
2019-10-21 05:39:56.974+0000 [id=396]	INFO	o.c.j.p.k.KubernetesSlave#deleteSlavePod: Terminated Kubernetes instance for agent kube-ops/jnlp-slave-4cjk4
2019-10-21 05:39:56.974+0000 [id=396]	INFO	o.c.j.p.k.KubernetesSlave#_terminate: Disconnected computer jnlp-slave-4cjk4
Terminated Kubernetes instance for agent kube-ops/jnlp-slave-4cjk4
Disconnected computer jnlp-slave-4cjk4

slave一直报离线，日志上面显示是配置错误，我安装你的配置也不行。

**Comment by DaiZero** [comment]
我的也是一直离线连接不上，有解决方案吗？

**Comment by wenpengfan** [comment]
> 我的也是一直离线连接不上，有解决方案吗？

我的版本改成1.13就好了

**Comment by DaiZero** [comment]
我的问题解决了,jnlp容器的配置按照如下来设置
```groovy
containerTemplate(name: 'jnlp', image: 'jenkins/jnlp-slave:3.35-5-alpine', args: '${computer.jnlpmac} ${computer.name}')
```
关键是`args`的设置内容，我的jenkinsfile内容如下
```groovy
def POD_LABEL = "vue-pod-${UUID.randomUUID().toString()}"

podTemplate (
    label: POD_LABEL, cloud: 'kubernetes',
    containers: [
         containerTemplate(name: 'jnlp', image: 'jenkins/jnlp-agent-docker', args: '${computer.jnlpmac} ${computer.name}'),
         containerTemplate(name: 'nodejs', image: "node:14-alpine", ttyEnabled: true, command: 'cat')
    ],
     volumes: [
        hostPathVolume(hostPath: '/var/run/docker.sock', mountPath:'/var/run/docker.sock')
    ]
) {
    node(POD_LABEL) {
        stage('code-checkout') {
            container('nodejs') {
                checkout scm
            }
          def packageJSON = readJSON file: 'package.json'
          build_tag = packageJSON.version
        }

        stage('code-build') {
            container('nodejs') {
                sh "npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/"
                sh 'npm install --unsafe-perm --registry=https://registry.npm.taobao.org'
                sh 'npm run build'
            }
        }

        stage('docker-build') {
            sh "docker build -t 192.168.1.11:6543/test/test-web:${build_tag} ."
        }

        stage('docker-push') {
            withCredentials([usernamePassword(credentialsId: 'localDocker', passwordVariable: 'localDockerPassword', usernameVariable: 'localDockerUser')]) {
            sh "docker login 192.168.1.11:6543 -u ${localDockerUser} -p ${localDockerPassword}"
            sh "docker push 192.168.1.11:6543/test/test-web:${build_tag}"
          }
        }

       stage('deploy') {
        input "是否部署到线上环境？"
       }
    }
}
```

**Comment by Jolin-blank** [comment]
调试的时候，为什么一直离线状态 
![image](https://user-images.githubusercontent.com/55644946/84387379-7b435880-ac25-11ea-9df9-b2cd3a194c25.png)

**Comment by Jolin-blank** [comment]
> 我的也是一直离线连接不上，有解决方案吗？

把默认运行的命令去掉就好了

**Comment by zjcnew** [comment]
我的容器运行时是containerd，不是docker，该怎么配置啊，一直提示连不上master。

2020-07-31 17:22:30.756+0000 [id=28]    INFO    o.c.j.p.k.KubernetesCloud#provision: Template for label haimaxy-jnlp: jnlp
2020-07-31 17:22:40.784+0000 [id=29]    INFO    hudson.slaves.NodeProvisioner#lambda$update$6: jnlp-x3d6w provisioning successfully completed. We have now 2 computer(s)
2020-07-31 17:22:40.806+0000 [id=458]   INFO    o.c.j.p.k.KubernetesLauncher#launch: Created Pod: default/jnlp-x3d6w
2020-07-31 17:22:40.866+0000 [id=460]   INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2020-07-31 17:22:40.916+0000 [id=458]   INFO    o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?



2020-07-31 17:27:40.884+0000 [id=458]   WARNING o.c.j.p.k.KubernetesLauncher#launch: Error in provisioning; agent=KubernetesSlave name: jnlp-x3d6w, template=PodTemplate{inheritFrom='', name='jnlp', namespace='default', hostNetwork=false, slaveConnectTimeout=300, activeDeadlineSeconds=500, label='haimaxy-jnlp', serviceAccount='jenkins', nodeSelector='', nodeUsageMode=EXCLUSIVE, workspaceVolume=EmptyDirWorkspaceVolume [memory=false], volumes=[HostPathVolume [mountPath=/var/run/docker.sock, hostPath=/var/run/docker.sock], HostPathVolume [mountPath=/root/.kube, hostPath=/root/.kube]], containers=[ContainerTemplate{name='jnlp', image='cygnf2eh.mirror.aliyuncs.com/cnych/jenkins:jnlp6', workingDir='/home/jenkins/agent', command='', args='', ttyEnabled=true, resourceRequestCpu='', resourceRequestMemory='', resourceLimitCpu='', resourceLimitMemory='', livenessProbe=org.csanchez.jenkins.plugins.kubernetes.ContainerLivenessProbe@622525d8}]}
io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [300000] milliseconds for [Pod] with name:[jnlp-x3d6w] in namespace [default].
        at org.csanchez.jenkins.plugins.kubernetes.AllContainersRunningPodWatcher.await(AllContainersRunningPodWatcher.java:97)
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:140)
        at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:296)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-07-31 17:27:40.884+0000 [id=458]   INFO    o.c.j.p.k.KubernetesSlave#_terminate: Terminating Kubernetes instance for agent jnlp-x3d6w
2020-07-31 17:27:40.934+0000 [id=458]   INFO    o.c.j.p.k.KubernetesSlave#deleteSlavePod: Terminated Kubernetes instance for agent default/jnlp-x3d6w
2020-07-31 17:27:40.934+0000 [id=458]   INFO    o.c.j.p.k.KubernetesSlave#_terminate: Disconnected computer jnlp-x3d6w
Terminated Kubernetes instance for agent default/jnlp-x3d6w
Disconnected computer jnlp-x3d6w

**Comment by xiahuhu1** [comment]
jenkins-slave 这个文件是在哪里下载啊？

**Comment by xiangys0134** [comment]
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  21s   default-scheduler  Successfully assigned kube-ops/xiangys0134-test-21-zvvcv-nvn8r-vw2g5 to k8s-node-01
  Normal  Pulling    20s   kubelet            Pulling image "busybox"
  Normal  Pulled     5s    kubelet            Successfully pulled image "busybox"
  Normal  Created    5s    kubelet            Created container busybox
  Normal  Started    5s    kubelet            Started container busybox
  Normal  Pulled     5s    kubelet            Container image "registry.cn-hangzhou.aliyuncs.com/xunce/jdk-base:rpmbuild-jdk-1.0.2" already present on machine
  Normal  Created    5s    kubelet            Created container jnlp
  Normal  Started    5s    kubelet            Started container jnlp
  Normal  Killing    1s    kubelet            Stopping container jnlp

jenkins集成到k8s时怎么支持多容器同时运行？

**Comment by xiangys0134** [comment]
agent {
    kubernetes {
      // label 'xc-vone-osp'

      cloud 'kubernetes'
      yaml """
apiVersion: v1
kind: Pod
metadata:
  namespace: kube-ops
labels:
  some-label: xc-vone-osp
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - cat
  - name: jnlp
    #image: cnych/jenkins:jnlp6
    image: registry.cn-hangzhou.aliyuncs.com/xunce/jdk-base:rpmbuild-jdk-1.0.2
    imagePullPolicy: "IfNotPresent"
    volumeMounts:
    - mountPath: "/var/run/docker.sock"
      name: "volume-0"
      readOnly: false
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  restartPolicy: "Never"
  securityContext: {}
  serviceAccount: "jenkins-ops"
  restartPolicy: "Never"
  imagePullSecrets:
  - name: "aliyun-image-secret"
  hostNetwork: false
  volumes:
    - hostPath:
        path: "/var/run/docker.sock"
      name: "volume-0"
    - emptyDir:
        medium: ""
      name: "workspace-volume"
"""
    }
  }

集成两个容器时jnlp容器退出了，难道是jenkins-slave脚本问题？

**Comment by LeoSuMou** [comment]
我按照你整个专题的教程部署的，所以k8s版本还是v1.10.0,部署的jenkins版本是2.440.3，搭配jnlp发现不能发送到node上面去，报错：
User
使用这个模板，报错
Error in provisioning; agent=KubernetesSlave name: jnlp-87jkv, template=PodTemplate{id='4b3ccff6-b5b4-462b-95a5-7cd77ad573bc', name='jnlp', namespace='kube-ops', label='leosumou-jnlp', serviceAccount='jenkins2', containers=[ContainerTemplate{name='jnlp', image='jenkins/inbound-agent:4.7-1', workingDir='/home/jenkins/agent', command='', args='', ttyEnabled=true, resourceRequestCpu='', resourceRequestMemory='', resourceRequestEphemeralStorage='', resourceLimitCpu='', resourceLimitMemory='', resourceLimitEphemeralStorage='', livenessProbe=ContainerLivenessProbe{execArgs='', timeoutSeconds=0, initialDelaySeconds=0, failureThreshold=0, periodSeconds=0, successThreshold=0}}]}
java.lang.IllegalStateException: Node was deleted, computer is null
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:203)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:297)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
好像是节点自动删除了，但我看访问都是没问题的，是不是k8s版本太低导致的呢？
